// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ylars.proto

#include "ylars.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ylars {
PROTOBUF_CONSTEXPR HostInfo::HostInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ip_)*/0u
  , /*decltype(_impl_.port_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HostInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HostInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HostInfoDefaultTypeInternal() {}
  union {
    HostInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HostInfoDefaultTypeInternal _HostInfo_default_instance_;
PROTOBUF_CONSTEXPR GetRouteRequest::GetRouteRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.modid_)*/0u
  , /*decltype(_impl_.cmdid_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetRouteRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetRouteRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetRouteRequestDefaultTypeInternal() {}
  union {
    GetRouteRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetRouteRequestDefaultTypeInternal _GetRouteRequest_default_instance_;
PROTOBUF_CONSTEXPR GetRouteResponse::GetRouteResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.host_)*/{}
  , /*decltype(_impl_.modid_)*/0u
  , /*decltype(_impl_.cmdid_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetRouteResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetRouteResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetRouteResponseDefaultTypeInternal() {}
  union {
    GetRouteResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetRouteResponseDefaultTypeInternal _GetRouteResponse_default_instance_;
PROTOBUF_CONSTEXPR HostCallResult::HostCallResult(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ip_)*/0u
  , /*decltype(_impl_.port_)*/0u
  , /*decltype(_impl_.succ_)*/0u
  , /*decltype(_impl_.err_)*/0u
  , /*decltype(_impl_.overload_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HostCallResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HostCallResultDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HostCallResultDefaultTypeInternal() {}
  union {
    HostCallResult _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HostCallResultDefaultTypeInternal _HostCallResult_default_instance_;
PROTOBUF_CONSTEXPR ReportStatusReq::ReportStatusReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.result_)*/{}
  , /*decltype(_impl_.modid_)*/0u
  , /*decltype(_impl_.cmdid_)*/0u
  , /*decltype(_impl_.caller_)*/0
  , /*decltype(_impl_.ts_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ReportStatusReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReportStatusReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReportStatusReqDefaultTypeInternal() {}
  union {
    ReportStatusReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReportStatusReqDefaultTypeInternal _ReportStatusReq_default_instance_;
PROTOBUF_CONSTEXPR GetHostRequest::GetHostRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.seq_)*/0u
  , /*decltype(_impl_.modid_)*/0u
  , /*decltype(_impl_.cmdid_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetHostRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetHostRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetHostRequestDefaultTypeInternal() {}
  union {
    GetHostRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetHostRequestDefaultTypeInternal _GetHostRequest_default_instance_;
PROTOBUF_CONSTEXPR GetHostResponse::GetHostResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.host_)*/nullptr
  , /*decltype(_impl_.seq_)*/0u
  , /*decltype(_impl_.modid_)*/0u
  , /*decltype(_impl_.cmdid_)*/0u
  , /*decltype(_impl_.retcode_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetHostResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetHostResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetHostResponseDefaultTypeInternal() {}
  union {
    GetHostResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetHostResponseDefaultTypeInternal _GetHostResponse_default_instance_;
PROTOBUF_CONSTEXPR ReportRequest::ReportRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.host_)*/nullptr
  , /*decltype(_impl_.modid_)*/0u
  , /*decltype(_impl_.cmdid_)*/0u
  , /*decltype(_impl_.issucc_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ReportRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReportRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReportRequestDefaultTypeInternal() {}
  union {
    ReportRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReportRequestDefaultTypeInternal _ReportRequest_default_instance_;
}  // namespace ylars
static ::_pb::Metadata file_level_metadata_ylars_2eproto[8];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ylars_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ylars_2eproto = nullptr;

const uint32_t TableStruct_ylars_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ylars::HostInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ylars::HostInfo, _impl_.ip_),
  PROTOBUF_FIELD_OFFSET(::ylars::HostInfo, _impl_.port_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ylars::GetRouteRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ylars::GetRouteRequest, _impl_.modid_),
  PROTOBUF_FIELD_OFFSET(::ylars::GetRouteRequest, _impl_.cmdid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ylars::GetRouteResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ylars::GetRouteResponse, _impl_.modid_),
  PROTOBUF_FIELD_OFFSET(::ylars::GetRouteResponse, _impl_.cmdid_),
  PROTOBUF_FIELD_OFFSET(::ylars::GetRouteResponse, _impl_.host_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ylars::HostCallResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ylars::HostCallResult, _impl_.ip_),
  PROTOBUF_FIELD_OFFSET(::ylars::HostCallResult, _impl_.port_),
  PROTOBUF_FIELD_OFFSET(::ylars::HostCallResult, _impl_.succ_),
  PROTOBUF_FIELD_OFFSET(::ylars::HostCallResult, _impl_.err_),
  PROTOBUF_FIELD_OFFSET(::ylars::HostCallResult, _impl_.overload_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ylars::ReportStatusReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ylars::ReportStatusReq, _impl_.modid_),
  PROTOBUF_FIELD_OFFSET(::ylars::ReportStatusReq, _impl_.cmdid_),
  PROTOBUF_FIELD_OFFSET(::ylars::ReportStatusReq, _impl_.caller_),
  PROTOBUF_FIELD_OFFSET(::ylars::ReportStatusReq, _impl_.result_),
  PROTOBUF_FIELD_OFFSET(::ylars::ReportStatusReq, _impl_.ts_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ylars::GetHostRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ylars::GetHostRequest, _impl_.seq_),
  PROTOBUF_FIELD_OFFSET(::ylars::GetHostRequest, _impl_.modid_),
  PROTOBUF_FIELD_OFFSET(::ylars::GetHostRequest, _impl_.cmdid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ylars::GetHostResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ylars::GetHostResponse, _impl_.seq_),
  PROTOBUF_FIELD_OFFSET(::ylars::GetHostResponse, _impl_.modid_),
  PROTOBUF_FIELD_OFFSET(::ylars::GetHostResponse, _impl_.cmdid_),
  PROTOBUF_FIELD_OFFSET(::ylars::GetHostResponse, _impl_.retcode_),
  PROTOBUF_FIELD_OFFSET(::ylars::GetHostResponse, _impl_.host_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ylars::ReportRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ylars::ReportRequest, _impl_.modid_),
  PROTOBUF_FIELD_OFFSET(::ylars::ReportRequest, _impl_.cmdid_),
  PROTOBUF_FIELD_OFFSET(::ylars::ReportRequest, _impl_.host_),
  PROTOBUF_FIELD_OFFSET(::ylars::ReportRequest, _impl_.issucc_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ylars::HostInfo)},
  { 8, -1, -1, sizeof(::ylars::GetRouteRequest)},
  { 16, -1, -1, sizeof(::ylars::GetRouteResponse)},
  { 25, -1, -1, sizeof(::ylars::HostCallResult)},
  { 36, -1, -1, sizeof(::ylars::ReportStatusReq)},
  { 47, -1, -1, sizeof(::ylars::GetHostRequest)},
  { 56, -1, -1, sizeof(::ylars::GetHostResponse)},
  { 67, -1, -1, sizeof(::ylars::ReportRequest)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ylars::_HostInfo_default_instance_._instance,
  &::ylars::_GetRouteRequest_default_instance_._instance,
  &::ylars::_GetRouteResponse_default_instance_._instance,
  &::ylars::_HostCallResult_default_instance_._instance,
  &::ylars::_ReportStatusReq_default_instance_._instance,
  &::ylars::_GetHostRequest_default_instance_._instance,
  &::ylars::_GetHostResponse_default_instance_._instance,
  &::ylars::_ReportRequest_default_instance_._instance,
};

const char descriptor_table_protodef_ylars_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\013ylars.proto\022\005ylars\"$\n\010HostInfo\022\n\n\002ip\030\001"
  " \001(\r\022\014\n\004port\030\002 \001(\r\"/\n\017GetRouteRequest\022\r\n"
  "\005modId\030\001 \001(\r\022\r\n\005cmdId\030\002 \001(\r\"O\n\020GetRouteR"
  "esponse\022\r\n\005modId\030\001 \001(\r\022\r\n\005cmdId\030\002 \001(\r\022\035\n"
  "\004host\030\003 \003(\0132\017.ylars.HostInfo\"W\n\016HostCall"
  "Result\022\n\n\002ip\030\001 \001(\r\022\014\n\004port\030\002 \001(\r\022\014\n\004succ"
  "\030\003 \001(\r\022\013\n\003err\030\004 \001(\r\022\020\n\010overload\030\005 \001(\010\"r\n"
  "\017ReportStatusReq\022\r\n\005modId\030\001 \001(\r\022\r\n\005cmdId"
  "\030\002 \001(\r\022\016\n\006caller\030\003 \001(\005\022%\n\006result\030\004 \003(\0132\025"
  ".ylars.HostCallResult\022\n\n\002ts\030\005 \001(\r\";\n\016Get"
  "HostRequest\022\013\n\003seq\030\001 \001(\r\022\r\n\005modid\030\002 \001(\r\022"
  "\r\n\005cmdid\030\003 \001(\r\"l\n\017GetHostResponse\022\013\n\003seq"
  "\030\001 \001(\r\022\r\n\005modid\030\002 \001(\r\022\r\n\005cmdid\030\003 \001(\r\022\017\n\007"
  "retcode\030\004 \001(\005\022\035\n\004host\030\005 \001(\0132\017.ylars.Host"
  "Info\"\\\n\rReportRequest\022\r\n\005modid\030\001 \001(\r\022\r\n\005"
  "cmdid\030\002 \001(\r\022\035\n\004host\030\003 \001(\0132\017.ylars.HostIn"
  "fo\022\016\n\006isSucc\030\004 \001(\010*\254\001\n\tMessageId\022\r\n\tID_U"
  "NKNOW\020\000\022\026\n\022ID_GetRouteRequest\020\001\022\027\n\023ID_Ge"
  "tRouteResponse\020\002\022\032\n\026ID_ReportStatusReque"
  "st\020\003\022\025\n\021ID_GetHostRequest\020\004\022\026\n\022ID_GetHos"
  "tResponse\020\005\022\024\n\020ID_ReportRequest\020\006*T\n\013Las"
  "tRetCode\022\014\n\010RET_SUCC\020\000\022\020\n\014RET_OVERLOAD\020\001"
  "\022\024\n\020RET_SYSTEM_ERROR\020\002\022\017\n\013RET_NOEXIST\020\003b"
  "\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_ylars_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ylars_2eproto = {
    false, false, 927, descriptor_table_protodef_ylars_2eproto,
    "ylars.proto",
    &descriptor_table_ylars_2eproto_once, nullptr, 0, 8,
    schemas, file_default_instances, TableStruct_ylars_2eproto::offsets,
    file_level_metadata_ylars_2eproto, file_level_enum_descriptors_ylars_2eproto,
    file_level_service_descriptors_ylars_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ylars_2eproto_getter() {
  return &descriptor_table_ylars_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ylars_2eproto(&descriptor_table_ylars_2eproto);
namespace ylars {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageId_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ylars_2eproto);
  return file_level_enum_descriptors_ylars_2eproto[0];
}
bool MessageId_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LastRetCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ylars_2eproto);
  return file_level_enum_descriptors_ylars_2eproto[1];
}
bool LastRetCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class HostInfo::_Internal {
 public:
};

HostInfo::HostInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ylars.HostInfo)
}
HostInfo::HostInfo(const HostInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HostInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ip_){}
    , decltype(_impl_.port_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.ip_, &from._impl_.ip_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.port_) -
    reinterpret_cast<char*>(&_impl_.ip_)) + sizeof(_impl_.port_));
  // @@protoc_insertion_point(copy_constructor:ylars.HostInfo)
}

inline void HostInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ip_){0u}
    , decltype(_impl_.port_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

HostInfo::~HostInfo() {
  // @@protoc_insertion_point(destructor:ylars.HostInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HostInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void HostInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HostInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:ylars.HostInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.ip_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.port_) -
      reinterpret_cast<char*>(&_impl_.ip_)) + sizeof(_impl_.port_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HostInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 ip = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.ip_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 port = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HostInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ylars.HostInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ip = 1;
  if (this->_internal_ip() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_ip(), target);
  }

  // uint32 port = 2;
  if (this->_internal_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_port(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ylars.HostInfo)
  return target;
}

size_t HostInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ylars.HostInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 ip = 1;
  if (this->_internal_ip() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_ip());
  }

  // uint32 port = 2;
  if (this->_internal_port() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_port());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HostInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HostInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HostInfo::GetClassData() const { return &_class_data_; }


void HostInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HostInfo*>(&to_msg);
  auto& from = static_cast<const HostInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ylars.HostInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_ip() != 0) {
    _this->_internal_set_ip(from._internal_ip());
  }
  if (from._internal_port() != 0) {
    _this->_internal_set_port(from._internal_port());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HostInfo::CopyFrom(const HostInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ylars.HostInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HostInfo::IsInitialized() const {
  return true;
}

void HostInfo::InternalSwap(HostInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HostInfo, _impl_.port_)
      + sizeof(HostInfo::_impl_.port_)
      - PROTOBUF_FIELD_OFFSET(HostInfo, _impl_.ip_)>(
          reinterpret_cast<char*>(&_impl_.ip_),
          reinterpret_cast<char*>(&other->_impl_.ip_));
}

::PROTOBUF_NAMESPACE_ID::Metadata HostInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ylars_2eproto_getter, &descriptor_table_ylars_2eproto_once,
      file_level_metadata_ylars_2eproto[0]);
}

// ===================================================================

class GetRouteRequest::_Internal {
 public:
};

GetRouteRequest::GetRouteRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ylars.GetRouteRequest)
}
GetRouteRequest::GetRouteRequest(const GetRouteRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetRouteRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.modid_){}
    , decltype(_impl_.cmdid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.modid_, &from._impl_.modid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.cmdid_) -
    reinterpret_cast<char*>(&_impl_.modid_)) + sizeof(_impl_.cmdid_));
  // @@protoc_insertion_point(copy_constructor:ylars.GetRouteRequest)
}

inline void GetRouteRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.modid_){0u}
    , decltype(_impl_.cmdid_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GetRouteRequest::~GetRouteRequest() {
  // @@protoc_insertion_point(destructor:ylars.GetRouteRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetRouteRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void GetRouteRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetRouteRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ylars.GetRouteRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.modid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.cmdid_) -
      reinterpret_cast<char*>(&_impl_.modid_)) + sizeof(_impl_.cmdid_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetRouteRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 modId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.modid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 cmdId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.cmdid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetRouteRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ylars.GetRouteRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 modId = 1;
  if (this->_internal_modid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_modid(), target);
  }

  // uint32 cmdId = 2;
  if (this->_internal_cmdid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_cmdid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ylars.GetRouteRequest)
  return target;
}

size_t GetRouteRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ylars.GetRouteRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 modId = 1;
  if (this->_internal_modid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_modid());
  }

  // uint32 cmdId = 2;
  if (this->_internal_cmdid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_cmdid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetRouteRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetRouteRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetRouteRequest::GetClassData() const { return &_class_data_; }


void GetRouteRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetRouteRequest*>(&to_msg);
  auto& from = static_cast<const GetRouteRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ylars.GetRouteRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_modid() != 0) {
    _this->_internal_set_modid(from._internal_modid());
  }
  if (from._internal_cmdid() != 0) {
    _this->_internal_set_cmdid(from._internal_cmdid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetRouteRequest::CopyFrom(const GetRouteRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ylars.GetRouteRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetRouteRequest::IsInitialized() const {
  return true;
}

void GetRouteRequest::InternalSwap(GetRouteRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetRouteRequest, _impl_.cmdid_)
      + sizeof(GetRouteRequest::_impl_.cmdid_)
      - PROTOBUF_FIELD_OFFSET(GetRouteRequest, _impl_.modid_)>(
          reinterpret_cast<char*>(&_impl_.modid_),
          reinterpret_cast<char*>(&other->_impl_.modid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GetRouteRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ylars_2eproto_getter, &descriptor_table_ylars_2eproto_once,
      file_level_metadata_ylars_2eproto[1]);
}

// ===================================================================

class GetRouteResponse::_Internal {
 public:
};

GetRouteResponse::GetRouteResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ylars.GetRouteResponse)
}
GetRouteResponse::GetRouteResponse(const GetRouteResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetRouteResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.host_){from._impl_.host_}
    , decltype(_impl_.modid_){}
    , decltype(_impl_.cmdid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.modid_, &from._impl_.modid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.cmdid_) -
    reinterpret_cast<char*>(&_impl_.modid_)) + sizeof(_impl_.cmdid_));
  // @@protoc_insertion_point(copy_constructor:ylars.GetRouteResponse)
}

inline void GetRouteResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.host_){arena}
    , decltype(_impl_.modid_){0u}
    , decltype(_impl_.cmdid_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GetRouteResponse::~GetRouteResponse() {
  // @@protoc_insertion_point(destructor:ylars.GetRouteResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetRouteResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.host_.~RepeatedPtrField();
}

void GetRouteResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetRouteResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ylars.GetRouteResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.host_.Clear();
  ::memset(&_impl_.modid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.cmdid_) -
      reinterpret_cast<char*>(&_impl_.modid_)) + sizeof(_impl_.cmdid_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetRouteResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 modId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.modid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 cmdId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.cmdid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .ylars.HostInfo host = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_host(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetRouteResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ylars.GetRouteResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 modId = 1;
  if (this->_internal_modid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_modid(), target);
  }

  // uint32 cmdId = 2;
  if (this->_internal_cmdid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_cmdid(), target);
  }

  // repeated .ylars.HostInfo host = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_host_size()); i < n; i++) {
    const auto& repfield = this->_internal_host(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ylars.GetRouteResponse)
  return target;
}

size_t GetRouteResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ylars.GetRouteResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ylars.HostInfo host = 3;
  total_size += 1UL * this->_internal_host_size();
  for (const auto& msg : this->_impl_.host_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 modId = 1;
  if (this->_internal_modid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_modid());
  }

  // uint32 cmdId = 2;
  if (this->_internal_cmdid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_cmdid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetRouteResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetRouteResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetRouteResponse::GetClassData() const { return &_class_data_; }


void GetRouteResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetRouteResponse*>(&to_msg);
  auto& from = static_cast<const GetRouteResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ylars.GetRouteResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.host_.MergeFrom(from._impl_.host_);
  if (from._internal_modid() != 0) {
    _this->_internal_set_modid(from._internal_modid());
  }
  if (from._internal_cmdid() != 0) {
    _this->_internal_set_cmdid(from._internal_cmdid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetRouteResponse::CopyFrom(const GetRouteResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ylars.GetRouteResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetRouteResponse::IsInitialized() const {
  return true;
}

void GetRouteResponse::InternalSwap(GetRouteResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.host_.InternalSwap(&other->_impl_.host_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetRouteResponse, _impl_.cmdid_)
      + sizeof(GetRouteResponse::_impl_.cmdid_)
      - PROTOBUF_FIELD_OFFSET(GetRouteResponse, _impl_.modid_)>(
          reinterpret_cast<char*>(&_impl_.modid_),
          reinterpret_cast<char*>(&other->_impl_.modid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GetRouteResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ylars_2eproto_getter, &descriptor_table_ylars_2eproto_once,
      file_level_metadata_ylars_2eproto[2]);
}

// ===================================================================

class HostCallResult::_Internal {
 public:
};

HostCallResult::HostCallResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ylars.HostCallResult)
}
HostCallResult::HostCallResult(const HostCallResult& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HostCallResult* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ip_){}
    , decltype(_impl_.port_){}
    , decltype(_impl_.succ_){}
    , decltype(_impl_.err_){}
    , decltype(_impl_.overload_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.ip_, &from._impl_.ip_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.overload_) -
    reinterpret_cast<char*>(&_impl_.ip_)) + sizeof(_impl_.overload_));
  // @@protoc_insertion_point(copy_constructor:ylars.HostCallResult)
}

inline void HostCallResult::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ip_){0u}
    , decltype(_impl_.port_){0u}
    , decltype(_impl_.succ_){0u}
    , decltype(_impl_.err_){0u}
    , decltype(_impl_.overload_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

HostCallResult::~HostCallResult() {
  // @@protoc_insertion_point(destructor:ylars.HostCallResult)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HostCallResult::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void HostCallResult::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HostCallResult::Clear() {
// @@protoc_insertion_point(message_clear_start:ylars.HostCallResult)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.ip_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.overload_) -
      reinterpret_cast<char*>(&_impl_.ip_)) + sizeof(_impl_.overload_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HostCallResult::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 ip = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.ip_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 port = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 succ = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.succ_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 err = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.err_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool overload = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.overload_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HostCallResult::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ylars.HostCallResult)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ip = 1;
  if (this->_internal_ip() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_ip(), target);
  }

  // uint32 port = 2;
  if (this->_internal_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_port(), target);
  }

  // uint32 succ = 3;
  if (this->_internal_succ() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_succ(), target);
  }

  // uint32 err = 4;
  if (this->_internal_err() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_err(), target);
  }

  // bool overload = 5;
  if (this->_internal_overload() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(5, this->_internal_overload(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ylars.HostCallResult)
  return target;
}

size_t HostCallResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ylars.HostCallResult)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 ip = 1;
  if (this->_internal_ip() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_ip());
  }

  // uint32 port = 2;
  if (this->_internal_port() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_port());
  }

  // uint32 succ = 3;
  if (this->_internal_succ() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_succ());
  }

  // uint32 err = 4;
  if (this->_internal_err() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_err());
  }

  // bool overload = 5;
  if (this->_internal_overload() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HostCallResult::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HostCallResult::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HostCallResult::GetClassData() const { return &_class_data_; }


void HostCallResult::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HostCallResult*>(&to_msg);
  auto& from = static_cast<const HostCallResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ylars.HostCallResult)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_ip() != 0) {
    _this->_internal_set_ip(from._internal_ip());
  }
  if (from._internal_port() != 0) {
    _this->_internal_set_port(from._internal_port());
  }
  if (from._internal_succ() != 0) {
    _this->_internal_set_succ(from._internal_succ());
  }
  if (from._internal_err() != 0) {
    _this->_internal_set_err(from._internal_err());
  }
  if (from._internal_overload() != 0) {
    _this->_internal_set_overload(from._internal_overload());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HostCallResult::CopyFrom(const HostCallResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ylars.HostCallResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HostCallResult::IsInitialized() const {
  return true;
}

void HostCallResult::InternalSwap(HostCallResult* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HostCallResult, _impl_.overload_)
      + sizeof(HostCallResult::_impl_.overload_)
      - PROTOBUF_FIELD_OFFSET(HostCallResult, _impl_.ip_)>(
          reinterpret_cast<char*>(&_impl_.ip_),
          reinterpret_cast<char*>(&other->_impl_.ip_));
}

::PROTOBUF_NAMESPACE_ID::Metadata HostCallResult::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ylars_2eproto_getter, &descriptor_table_ylars_2eproto_once,
      file_level_metadata_ylars_2eproto[3]);
}

// ===================================================================

class ReportStatusReq::_Internal {
 public:
};

ReportStatusReq::ReportStatusReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ylars.ReportStatusReq)
}
ReportStatusReq::ReportStatusReq(const ReportStatusReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ReportStatusReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.result_){from._impl_.result_}
    , decltype(_impl_.modid_){}
    , decltype(_impl_.cmdid_){}
    , decltype(_impl_.caller_){}
    , decltype(_impl_.ts_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.modid_, &from._impl_.modid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.ts_) -
    reinterpret_cast<char*>(&_impl_.modid_)) + sizeof(_impl_.ts_));
  // @@protoc_insertion_point(copy_constructor:ylars.ReportStatusReq)
}

inline void ReportStatusReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.result_){arena}
    , decltype(_impl_.modid_){0u}
    , decltype(_impl_.cmdid_){0u}
    , decltype(_impl_.caller_){0}
    , decltype(_impl_.ts_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ReportStatusReq::~ReportStatusReq() {
  // @@protoc_insertion_point(destructor:ylars.ReportStatusReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ReportStatusReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.result_.~RepeatedPtrField();
}

void ReportStatusReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ReportStatusReq::Clear() {
// @@protoc_insertion_point(message_clear_start:ylars.ReportStatusReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_.Clear();
  ::memset(&_impl_.modid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.ts_) -
      reinterpret_cast<char*>(&_impl_.modid_)) + sizeof(_impl_.ts_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReportStatusReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 modId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.modid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 cmdId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.cmdid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 caller = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.caller_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .ylars.HostCallResult result = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_result(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // uint32 ts = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.ts_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ReportStatusReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ylars.ReportStatusReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 modId = 1;
  if (this->_internal_modid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_modid(), target);
  }

  // uint32 cmdId = 2;
  if (this->_internal_cmdid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_cmdid(), target);
  }

  // int32 caller = 3;
  if (this->_internal_caller() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_caller(), target);
  }

  // repeated .ylars.HostCallResult result = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_result_size()); i < n; i++) {
    const auto& repfield = this->_internal_result(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  // uint32 ts = 5;
  if (this->_internal_ts() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(5, this->_internal_ts(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ylars.ReportStatusReq)
  return target;
}

size_t ReportStatusReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ylars.ReportStatusReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ylars.HostCallResult result = 4;
  total_size += 1UL * this->_internal_result_size();
  for (const auto& msg : this->_impl_.result_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 modId = 1;
  if (this->_internal_modid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_modid());
  }

  // uint32 cmdId = 2;
  if (this->_internal_cmdid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_cmdid());
  }

  // int32 caller = 3;
  if (this->_internal_caller() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_caller());
  }

  // uint32 ts = 5;
  if (this->_internal_ts() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_ts());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReportStatusReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ReportStatusReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReportStatusReq::GetClassData() const { return &_class_data_; }


void ReportStatusReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ReportStatusReq*>(&to_msg);
  auto& from = static_cast<const ReportStatusReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ylars.ReportStatusReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.result_.MergeFrom(from._impl_.result_);
  if (from._internal_modid() != 0) {
    _this->_internal_set_modid(from._internal_modid());
  }
  if (from._internal_cmdid() != 0) {
    _this->_internal_set_cmdid(from._internal_cmdid());
  }
  if (from._internal_caller() != 0) {
    _this->_internal_set_caller(from._internal_caller());
  }
  if (from._internal_ts() != 0) {
    _this->_internal_set_ts(from._internal_ts());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ReportStatusReq::CopyFrom(const ReportStatusReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ylars.ReportStatusReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReportStatusReq::IsInitialized() const {
  return true;
}

void ReportStatusReq::InternalSwap(ReportStatusReq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.result_.InternalSwap(&other->_impl_.result_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReportStatusReq, _impl_.ts_)
      + sizeof(ReportStatusReq::_impl_.ts_)
      - PROTOBUF_FIELD_OFFSET(ReportStatusReq, _impl_.modid_)>(
          reinterpret_cast<char*>(&_impl_.modid_),
          reinterpret_cast<char*>(&other->_impl_.modid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ReportStatusReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ylars_2eproto_getter, &descriptor_table_ylars_2eproto_once,
      file_level_metadata_ylars_2eproto[4]);
}

// ===================================================================

class GetHostRequest::_Internal {
 public:
};

GetHostRequest::GetHostRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ylars.GetHostRequest)
}
GetHostRequest::GetHostRequest(const GetHostRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetHostRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.seq_){}
    , decltype(_impl_.modid_){}
    , decltype(_impl_.cmdid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.seq_, &from._impl_.seq_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.cmdid_) -
    reinterpret_cast<char*>(&_impl_.seq_)) + sizeof(_impl_.cmdid_));
  // @@protoc_insertion_point(copy_constructor:ylars.GetHostRequest)
}

inline void GetHostRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.seq_){0u}
    , decltype(_impl_.modid_){0u}
    , decltype(_impl_.cmdid_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GetHostRequest::~GetHostRequest() {
  // @@protoc_insertion_point(destructor:ylars.GetHostRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetHostRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void GetHostRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetHostRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ylars.GetHostRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.seq_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.cmdid_) -
      reinterpret_cast<char*>(&_impl_.seq_)) + sizeof(_impl_.cmdid_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetHostRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 seq = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.seq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 modid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.modid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 cmdid = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.cmdid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetHostRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ylars.GetHostRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 seq = 1;
  if (this->_internal_seq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_seq(), target);
  }

  // uint32 modid = 2;
  if (this->_internal_modid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_modid(), target);
  }

  // uint32 cmdid = 3;
  if (this->_internal_cmdid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_cmdid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ylars.GetHostRequest)
  return target;
}

size_t GetHostRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ylars.GetHostRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 seq = 1;
  if (this->_internal_seq() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_seq());
  }

  // uint32 modid = 2;
  if (this->_internal_modid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_modid());
  }

  // uint32 cmdid = 3;
  if (this->_internal_cmdid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_cmdid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetHostRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetHostRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetHostRequest::GetClassData() const { return &_class_data_; }


void GetHostRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetHostRequest*>(&to_msg);
  auto& from = static_cast<const GetHostRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ylars.GetHostRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_seq() != 0) {
    _this->_internal_set_seq(from._internal_seq());
  }
  if (from._internal_modid() != 0) {
    _this->_internal_set_modid(from._internal_modid());
  }
  if (from._internal_cmdid() != 0) {
    _this->_internal_set_cmdid(from._internal_cmdid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetHostRequest::CopyFrom(const GetHostRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ylars.GetHostRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetHostRequest::IsInitialized() const {
  return true;
}

void GetHostRequest::InternalSwap(GetHostRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetHostRequest, _impl_.cmdid_)
      + sizeof(GetHostRequest::_impl_.cmdid_)
      - PROTOBUF_FIELD_OFFSET(GetHostRequest, _impl_.seq_)>(
          reinterpret_cast<char*>(&_impl_.seq_),
          reinterpret_cast<char*>(&other->_impl_.seq_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GetHostRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ylars_2eproto_getter, &descriptor_table_ylars_2eproto_once,
      file_level_metadata_ylars_2eproto[5]);
}

// ===================================================================

class GetHostResponse::_Internal {
 public:
  static const ::ylars::HostInfo& host(const GetHostResponse* msg);
};

const ::ylars::HostInfo&
GetHostResponse::_Internal::host(const GetHostResponse* msg) {
  return *msg->_impl_.host_;
}
GetHostResponse::GetHostResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ylars.GetHostResponse)
}
GetHostResponse::GetHostResponse(const GetHostResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetHostResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.host_){nullptr}
    , decltype(_impl_.seq_){}
    , decltype(_impl_.modid_){}
    , decltype(_impl_.cmdid_){}
    , decltype(_impl_.retcode_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_host()) {
    _this->_impl_.host_ = new ::ylars::HostInfo(*from._impl_.host_);
  }
  ::memcpy(&_impl_.seq_, &from._impl_.seq_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.retcode_) -
    reinterpret_cast<char*>(&_impl_.seq_)) + sizeof(_impl_.retcode_));
  // @@protoc_insertion_point(copy_constructor:ylars.GetHostResponse)
}

inline void GetHostResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.host_){nullptr}
    , decltype(_impl_.seq_){0u}
    , decltype(_impl_.modid_){0u}
    , decltype(_impl_.cmdid_){0u}
    , decltype(_impl_.retcode_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GetHostResponse::~GetHostResponse() {
  // @@protoc_insertion_point(destructor:ylars.GetHostResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetHostResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.host_;
}

void GetHostResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetHostResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ylars.GetHostResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.host_ != nullptr) {
    delete _impl_.host_;
  }
  _impl_.host_ = nullptr;
  ::memset(&_impl_.seq_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.retcode_) -
      reinterpret_cast<char*>(&_impl_.seq_)) + sizeof(_impl_.retcode_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetHostResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 seq = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.seq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 modid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.modid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 cmdid = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.cmdid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 retcode = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.retcode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ylars.HostInfo host = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_host(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetHostResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ylars.GetHostResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 seq = 1;
  if (this->_internal_seq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_seq(), target);
  }

  // uint32 modid = 2;
  if (this->_internal_modid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_modid(), target);
  }

  // uint32 cmdid = 3;
  if (this->_internal_cmdid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_cmdid(), target);
  }

  // int32 retcode = 4;
  if (this->_internal_retcode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_retcode(), target);
  }

  // .ylars.HostInfo host = 5;
  if (this->_internal_has_host()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::host(this),
        _Internal::host(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ylars.GetHostResponse)
  return target;
}

size_t GetHostResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ylars.GetHostResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .ylars.HostInfo host = 5;
  if (this->_internal_has_host()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.host_);
  }

  // uint32 seq = 1;
  if (this->_internal_seq() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_seq());
  }

  // uint32 modid = 2;
  if (this->_internal_modid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_modid());
  }

  // uint32 cmdid = 3;
  if (this->_internal_cmdid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_cmdid());
  }

  // int32 retcode = 4;
  if (this->_internal_retcode() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_retcode());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetHostResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetHostResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetHostResponse::GetClassData() const { return &_class_data_; }


void GetHostResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetHostResponse*>(&to_msg);
  auto& from = static_cast<const GetHostResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ylars.GetHostResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_host()) {
    _this->_internal_mutable_host()->::ylars::HostInfo::MergeFrom(
        from._internal_host());
  }
  if (from._internal_seq() != 0) {
    _this->_internal_set_seq(from._internal_seq());
  }
  if (from._internal_modid() != 0) {
    _this->_internal_set_modid(from._internal_modid());
  }
  if (from._internal_cmdid() != 0) {
    _this->_internal_set_cmdid(from._internal_cmdid());
  }
  if (from._internal_retcode() != 0) {
    _this->_internal_set_retcode(from._internal_retcode());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetHostResponse::CopyFrom(const GetHostResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ylars.GetHostResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetHostResponse::IsInitialized() const {
  return true;
}

void GetHostResponse::InternalSwap(GetHostResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetHostResponse, _impl_.retcode_)
      + sizeof(GetHostResponse::_impl_.retcode_)
      - PROTOBUF_FIELD_OFFSET(GetHostResponse, _impl_.host_)>(
          reinterpret_cast<char*>(&_impl_.host_),
          reinterpret_cast<char*>(&other->_impl_.host_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GetHostResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ylars_2eproto_getter, &descriptor_table_ylars_2eproto_once,
      file_level_metadata_ylars_2eproto[6]);
}

// ===================================================================

class ReportRequest::_Internal {
 public:
  static const ::ylars::HostInfo& host(const ReportRequest* msg);
};

const ::ylars::HostInfo&
ReportRequest::_Internal::host(const ReportRequest* msg) {
  return *msg->_impl_.host_;
}
ReportRequest::ReportRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ylars.ReportRequest)
}
ReportRequest::ReportRequest(const ReportRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ReportRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.host_){nullptr}
    , decltype(_impl_.modid_){}
    , decltype(_impl_.cmdid_){}
    , decltype(_impl_.issucc_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_host()) {
    _this->_impl_.host_ = new ::ylars::HostInfo(*from._impl_.host_);
  }
  ::memcpy(&_impl_.modid_, &from._impl_.modid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.issucc_) -
    reinterpret_cast<char*>(&_impl_.modid_)) + sizeof(_impl_.issucc_));
  // @@protoc_insertion_point(copy_constructor:ylars.ReportRequest)
}

inline void ReportRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.host_){nullptr}
    , decltype(_impl_.modid_){0u}
    , decltype(_impl_.cmdid_){0u}
    , decltype(_impl_.issucc_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ReportRequest::~ReportRequest() {
  // @@protoc_insertion_point(destructor:ylars.ReportRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ReportRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.host_;
}

void ReportRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ReportRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ylars.ReportRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.host_ != nullptr) {
    delete _impl_.host_;
  }
  _impl_.host_ = nullptr;
  ::memset(&_impl_.modid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.issucc_) -
      reinterpret_cast<char*>(&_impl_.modid_)) + sizeof(_impl_.issucc_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReportRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 modid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.modid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 cmdid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.cmdid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ylars.HostInfo host = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_host(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool isSucc = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.issucc_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ReportRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ylars.ReportRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 modid = 1;
  if (this->_internal_modid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_modid(), target);
  }

  // uint32 cmdid = 2;
  if (this->_internal_cmdid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_cmdid(), target);
  }

  // .ylars.HostInfo host = 3;
  if (this->_internal_has_host()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::host(this),
        _Internal::host(this).GetCachedSize(), target, stream);
  }

  // bool isSucc = 4;
  if (this->_internal_issucc() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_issucc(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ylars.ReportRequest)
  return target;
}

size_t ReportRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ylars.ReportRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .ylars.HostInfo host = 3;
  if (this->_internal_has_host()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.host_);
  }

  // uint32 modid = 1;
  if (this->_internal_modid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_modid());
  }

  // uint32 cmdid = 2;
  if (this->_internal_cmdid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_cmdid());
  }

  // bool isSucc = 4;
  if (this->_internal_issucc() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReportRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ReportRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReportRequest::GetClassData() const { return &_class_data_; }


void ReportRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ReportRequest*>(&to_msg);
  auto& from = static_cast<const ReportRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ylars.ReportRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_host()) {
    _this->_internal_mutable_host()->::ylars::HostInfo::MergeFrom(
        from._internal_host());
  }
  if (from._internal_modid() != 0) {
    _this->_internal_set_modid(from._internal_modid());
  }
  if (from._internal_cmdid() != 0) {
    _this->_internal_set_cmdid(from._internal_cmdid());
  }
  if (from._internal_issucc() != 0) {
    _this->_internal_set_issucc(from._internal_issucc());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ReportRequest::CopyFrom(const ReportRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ylars.ReportRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReportRequest::IsInitialized() const {
  return true;
}

void ReportRequest::InternalSwap(ReportRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReportRequest, _impl_.issucc_)
      + sizeof(ReportRequest::_impl_.issucc_)
      - PROTOBUF_FIELD_OFFSET(ReportRequest, _impl_.host_)>(
          reinterpret_cast<char*>(&_impl_.host_),
          reinterpret_cast<char*>(&other->_impl_.host_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ReportRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ylars_2eproto_getter, &descriptor_table_ylars_2eproto_once,
      file_level_metadata_ylars_2eproto[7]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ylars
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ylars::HostInfo*
Arena::CreateMaybeMessage< ::ylars::HostInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ylars::HostInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::ylars::GetRouteRequest*
Arena::CreateMaybeMessage< ::ylars::GetRouteRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ylars::GetRouteRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::ylars::GetRouteResponse*
Arena::CreateMaybeMessage< ::ylars::GetRouteResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ylars::GetRouteResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::ylars::HostCallResult*
Arena::CreateMaybeMessage< ::ylars::HostCallResult >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ylars::HostCallResult >(arena);
}
template<> PROTOBUF_NOINLINE ::ylars::ReportStatusReq*
Arena::CreateMaybeMessage< ::ylars::ReportStatusReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ylars::ReportStatusReq >(arena);
}
template<> PROTOBUF_NOINLINE ::ylars::GetHostRequest*
Arena::CreateMaybeMessage< ::ylars::GetHostRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ylars::GetHostRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::ylars::GetHostResponse*
Arena::CreateMaybeMessage< ::ylars::GetHostResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ylars::GetHostResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::ylars::ReportRequest*
Arena::CreateMaybeMessage< ::ylars::ReportRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ylars::ReportRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
